###############################################################
# Program:
#     Assignment 05, Product inventory
#     Brother Dudley, CS165
# Author:
#     Joshua Pearson
# Summary:
#     Put your summary code here... 
###############################################################


# We will learn fancier compilation steps later, but this is
# good enough for now...
a.out : product.h product.cpp assign05.cpp
	g++ product.cpp assign05.cpp

