###############################################################
# Program:
#     Assignment 05, Order Tracking
#     Brother Dudley, CS165
# Author:
#     Joshua Pearson
# Summary:
#     Does what Main says. (Provides a library for managing
#     orders, customers, addresses and products)
###############################################################


# We will learn fancier compilation steps later, but this is
# good enough for now...
a.out : product.h product.cpp address.h address.cpp customer.h customer.cpp order.h order.cpp assign05.cpp
	g++ product.cpp address.cpp customer.cpp order.cpp assign05.cpp

